# Permalinks
permalink:           pretty

# Setup
title:               敏在悉尼等你
tagline:             Initial Commit
url:                 http://mizhao2018.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Miranda Zhao
  url:               https://www.linkedin.com/in/miranda-runmin-zhao-98225027/
  email:             mirandazhao2014@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/mizhao2018

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
